
development:
  adapter: postgresql
  encoding: unicode
  database: chicoplusplus_development
  pool: 5
  username: chicoplusplus
  password: chicoplusplus
test:
  adapter: postgresql
  encoding: unicode
  database: chicoplusplus_test
  pool: 5
  username: chicoplusplus
  password: chicoplusplus
production:
  adapter: postgresql
  encoding: unicode
  database: chicoplusplus_production
  pool: 5
  username: chicoplusplus
  password: chicoplusplus
