#!/usr/bin/env bash
SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_DIR/../config/env-test.bash
bundle exec kicker -r ruby -r ignore -r rails_minitest -b 'spin push'

