#!/usr/bin/env bash
SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_DIR/../config/env-test.bash

WHICH=$1
if [[ "$WHICH" == "" ]]; then
  WHICH="all"
fi

bundle exec rake test:$WHICH
